spring.application.name=bookstore_mongodb

spring.data.mongodb.uri=mongodb://localhost:27017/bookstore

logging.level.org.springframework.data.mongodb.core=DEBUG

jwt.secret=cpsc449-bookstore-secret-key-must-be-at-least-256-bits-long!
jwt.expiration=84000000
